objc_library(
    name = 'Objc',
    enable_modules = True,
    srcs = glob(['**/*.m']),
    hdrs = glob(['**/*.h']),
    deps = [
        '//ios/EmptySwift',
    ],
    visibility = ['//visibility:public'],
)
