objc_library(
    name = 'ObjcLibrary',
    module_name = 'ObjcLibrary',
    enable_modules = True,
    srcs = glob(['**/*.m']),
    hdrs = glob(['**/*.h']),
    visibility = ['//visibility:public'],
)
